'use client';
import Dashboard from '@/components/dashboard';
import CustomTabs from '@/navigation/tabs';
import { Metadata } from 'next';
import { useEffect, useState } from 'react';
import { enableReactTracking } from '@legendapp/state/config/enableReactTracking';
import {
	configureObservablePersistence,
	persistObservable,
} from '@legendapp/state/persist';
import { ObservablePersistLocalStorage } from '@legendapp/state/persist-plugins/local-storage';
import { observable } from '@legendapp/state';
import Results from '@/components/results';

const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

enableReactTracking({
	auto: true,
});

configureObservablePersistence({
	pluginLocal: ObservablePersistLocalStorage,
});

type TGlobal = {
	search: string;
	currentPageHome: 'home' | 'result';
	pageSize: number | number[];
	page: number;
	totalResults: number;
};

export const globalState$ = observable({
	search: '',
	currentPageHome: 'home',
	pageSize: 3,
	page: 1,
	totalResults: 0,
} as TGlobal);

persistObservable(globalState$, {
	local: 'globalState$aha',
});

export default function Home({ children }: { children: React.ReactNode }) {
	const [isDesktop, setIsDesktop] = useState(true);

	useEffect(() => {
		const handleResize = () => {
			setIsDesktop(window.innerWidth >= 1440);
		};

		handleResize();

		window.addEventListener('resize', handleResize);

		return () => {
			window.removeEventListener('resize', handleResize);
		};
	}, []);

	return (
		<main className='flex min-h-screen  flex-row w-full justify-center bg-[#1F1F1F]'>
			<head>
				<title>
					AHA |{' '}
					{globalState$.get().currentPageHome === 'home' ? 'Home' : 'Results'}
				</title>
				<meta name='description' content='Awesome AHA' />
			</head>
			{globalState$.get().currentPageHome === 'home' ? (
				<Dashboard />
			) : (
				<Results />
			)}
			{isDesktop && (
				<div className='flex w-[375px]'>
					<CustomTabs />
				</div>
			)}
		</main>
	);
}
