'use client';
import BottomNav from '@/components/bottom-nav';
import Dashboard from '@/components/dashboard';
import Sidebar from '@/components/sidebar';
import { Metadata } from 'next';
import Image from 'next/image';
import { useEffect, useState } from 'react';

const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function Home({ children }: { children: React.ReactNode }) {
	return (
		<main className='flex min-h-screen flex-row w-full justify-center'>
			<head>
				<title>AHA | Home</title>
				<meta name='description' content='Awesome AHA' />
			</head>
			<Dashboard />
			<div>Followers</div>
		</main>
	);
}
